### ISSUE TITLE
模块与模块之间互相引用好像会报错诶…

### ISSUE THREAD

**Issue by akirarika** [hyb1996/Auto.js#437]
test1.js
```javascript
module.exports = {
    test: function () {
        return 'test!'
    }
}
```

test2.js
```javascript
var test1 = require('test1.js')

module.exports = {
    test: function () {
        console.log(test1.test())
    }
}
```

main.js
```javascript
console.show()

// 执行报错，报错代码如下图
// var test2 = require('test2.js')
// test2.test()

// 执行并没有报错
var test1 = require('test1.js')
console.log(test1.test())
```
![_player_20190108120608](https://user-images.githubusercontent.com/33272184/50809347-ece6eb00-133d-11e9-9312-9f343ae7286b.png)

**Comment by akirarika** [comment]
Update.. 忘记说环境了……
```yml
AutoJS Version: 4.0.5Alpha
Android Version: 9.0
Android Emulator: Genymotion
```
